import { useState } from 'react';
import { Sparkles, ListChecks, Gauge, AlertTriangle } from 'lucide-react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { getVerdictMeta, humanize } from '@/lib/risk';
import { cn } from '@/lib/utils';

const ruleLabel = (rule) => {
  if (typeof rule === 'string') return humanize(rule.replace(/[:_]/g, ' '));
  if (rule?.rule) return humanize(String(rule.rule).replace(/[:_]/g, ' '));
  if (rule?.id) return humanize(String(rule.id).replace(/[:_]/g, ' '));
  return 'Rule';
};

const rulePoints = (rule) =>
  typeof rule === 'object' ? rule.points ?? rule.totalPoints ?? null : null;

function ScoreBar({ label, value, max = 100, tone }) {
  const pct = Math.max(0, Math.min(100, (Number(value) / max) * 100 || 0));
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between text-xs">
        <span className="text-muted-foreground">{label}</span>
        <span className="font-medium tabular-nums">{value ?? 0}</span>
      </div>
      <div className="h-1.5 w-full overflow-hidden rounded-full bg-muted">
        <div
          className={cn('h-full rounded-full transition-all', tone)}
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

const RULES_PREVIEW = 3;

export function ScanDetails({ scan }) {
  const [showAllRules, setShowAllRules] = useState(false);

  if (!scan) return null;

  const verdictMeta = getVerdictMeta(scan.verdict);
  const triggered = Array.isArray(scan.triggeredRules) ? scan.triggeredRules : [];
  const visibleRules = showAllRules ? triggered : triggered.slice(0, RULES_PREVIEW);
  const hiddenRulesCount = triggered.length - RULES_PREVIEW;
  const reasons = Array.isArray(scan.reasons) ? scan.reasons : [];
  const summary = scan.aiExplanation?.summary;
  const aiSource = scan.aiExplanationMeta?.source;
  const aiStatus = scan.aiExplanationMeta?.status;
  const ollamaUnavailable = aiSource === 'fallback' || aiStatus === 'fallback';

  return (
    <div className="space-y-4">
      {/* Ollama unavailable warning */}
      {ollamaUnavailable && (
        <div className="flex items-start gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2.5 text-sm text-amber-400">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>AI model (Ollama) was unavailable — explanation generated by rule-based fallback.</span>
        </div>
      )}

      {/* AI explanation — plain-language summary */}
      {summary && (
        <Card className={ollamaUnavailable ? 'border-border' : 'border-primary/25 bg-primary/5'}>
          <CardHeader className="flex-row items-center gap-2 space-y-0">
            <Sparkles className={cn('h-4 w-4', ollamaUnavailable ? 'text-muted-foreground' : 'text-primary')} />
            <CardTitle className="text-sm">
              {ollamaUnavailable ? 'Rule-based explanation' : 'AI explanation'}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed text-foreground/90">{summary}</p>
          </CardContent>
        </Card>
      )}

      {/* Score breakdown */}
      <Card>
        <CardHeader className="flex-row items-center gap-2 space-y-0">
          <Gauge className="h-4 w-4 text-muted-foreground" />
          <CardTitle className="text-sm">Risk score</CardTitle>
          <span className={cn('ml-auto text-sm font-semibold', verdictMeta.tone.text)}>
            {verdictMeta.label}
          </span>
        </CardHeader>
        <CardContent className="space-y-3">
          <ScoreBar label="Total score" value={scan.score} tone="bg-primary" />
          <div className="grid grid-cols-2 gap-4">
            <ScoreBar label="Rule signals" value={scan.ruleScore} tone="bg-chart-3" />
            <ScoreBar label="AI signals" value={scan.aiScore} tone="bg-chart-1" />
          </div>
        </CardContent>
      </Card>

      {/* Triggered rules */}
      <Card>
        <CardHeader className="flex-row items-center gap-2 space-y-0">
          <ListChecks className="h-4 w-4 text-muted-foreground" />
          <CardTitle className="text-sm">
            Triggered rules{triggered.length ? ` (${triggered.length})` : ''}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {triggered.length === 0 && reasons.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No rules were triggered for this message.
            </p>
          ) : (
            <>
              <ul className="space-y-2">
                {visibleRules.map((rule, i) => (
                  <li
                    key={i}
                    className="flex items-center justify-between gap-3 rounded-md border border-border/60 bg-background/40 px-3 py-2 text-sm"
                  >
                    <span>{ruleLabel(rule)}</span>
                    {rulePoints(rule) != null && (
                      <Badge variant="muted" className="tabular-nums">
                        +{rulePoints(rule)}
                      </Badge>
                    )}
                  </li>
                ))}
                {triggered.length === 0 &&
                  reasons.map((reason, i) => (
                    <li key={i} className="text-sm text-muted-foreground">
                      • {reason}
                    </li>
                  ))}
              </ul>
              {hiddenRulesCount > 0 && (
                <button
                  onClick={() => setShowAllRules((v) => !v)}
                  className="mt-2 text-xs text-muted-foreground underline-offset-2 hover:text-foreground hover:underline"
                >
                  {showAllRules ? 'Show less' : `Show ${hiddenRulesCount} more`}
                </button>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
